version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server/keys:/app/keys

  client:
    build: ./client
    volumes:
      - ./client/keys:/app/keys
